runtime: nodejs
api_version: 19.7.0
threadsafe: yes

handlers:
- url: .*
  script: auto

libraries:
- name: webapp2
  version: "2.5.2"

entrypoint: "node app.js"

# runtime: nodejs20 # or another supported version

# instance_class: F2

# env_variables:
#   BUCKET_NAME: "example-gcs-bucket"

# handlers:
# - url: /stylesheets
#   static_dir: stylesheets

# - url: /.*
#   secure: always
#   redirect_http_response_code: 301
#   script: auto